@echo off
echo Starting SendMessenger...
echo Starting Backend Server...
start cmd /k "cd server && node index.js"
echo Starting Frontend Client...
start cmd /k "cd client && npm run dev"
echo Done! Please scan the QR code in the browser window.
